#!/bin/bash

#
# Home Directory Backup Script
#

#    -z is to enable compression
#    -v verbose
#    -r indicates recursive

rsync -zvr dirtobackup backupdir 2>/dev/null

# Backup keepass.kdb file with date in the filename.

#XXX Encrypt backup
tar --listed-incremental=/run/media/bullshark/Storage/Backup/snapshot \
  -cJpf /run/media/bullshark/Storage/Backup/home-backup-`date +%d-%m-%Y`.tar.xz \
  /home/bullshark/{Documents,Downloads,Pictures,Music,.config,.Xresources,.xinitrc,.i3,.mozilla,.zshrc}

