#!/bin/bash
#
# Find all downloaded podcasts, shuffle them randomly, add at most 200 to a playlist, and play them in vlc with fullscreen.
#

find /run/media/bullshark/Storage/gPodder/Downloads/ -type f -iname "*.mp4" -type f | shuf | head -n 200 > /tmp/podcast_shuffle.m3u
vlc -f /tmp/podcast_shuffle.m3u

# vi: ft=sh

